server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      client:
        config:
          customer-service:
            url: http://localhost:8081
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            dismiss404: true